// constants.js
// Static config/data used across the app. Kept separate so components
// don't need to re-import the whole main file just to read a color map.

export const API_BASE_URL =
  import.meta.env.VITE_API_BASE_URL || "http://127.0.0.1:8000";

export const FALLBACK_STOPS = [
  {
    label: "Day 1: Arrival & Colombo",
    title: "Colombo City Tour",
    place_name: "Colombo City Tour",
    city: "Colombo",
    location: "Colombo",
    category: "City Life",
    lat: 6.9271,
    lng: 79.8612,
    day: 1,
    info: "Explore the vibrant capital city with modern life and colonial heritage.",
    why_we_recommend:
      "Explore the vibrant capital city with modern life and colonial heritage.",
    emoji: "🏙️",
    image: "/places/colombo.jpg",
    match: 94,
    match_percentage: 94,
    distance: "0 km",
    time: "Arrival",
    bestTime: "Evening",
  },
  {
    label: "Day 2: Sigiriya Rock",
    title: "Sigiriya Rock Fortress",
    place_name: "Sigiriya Rock Fortress",
    city: "Sigiriya",
    location: "Sigiriya, Central Province",
    category: "Historic Sites",
    lat: 7.957,
    lng: 80.7603,
    day: 2,
    info: "Ancient rock fortress and UNESCO World Heritage Site with stunning views.",
    why_we_recommend:
      "Ancient rock fortress and UNESCO World Heritage Site with stunning views.",
    emoji: "🪨",
    image: "/places/sigiriya.jpg",
    match: 95,
    match_percentage: 95,
    distance: "169 km",
    time: "3h 45m",
    bestTime: "Morning",
  },
  {
    label: "Day 3: Kandy Temple",
    title: "Temple of the Tooth",
    place_name: "Temple of the Tooth",
    city: "Kandy",
    location: "Kandy, Central Province",
    category: "Religious Sites",
    lat: 7.2906,
    lng: 80.6337,
    day: 3,
    info: "Sacred Buddhist temple housing the relic of the Tooth of Buddha.",
    why_we_recommend:
      "Sacred Buddhist temple housing the relic of the Tooth of Buddha.",
    emoji: "🛕",
    image: "/places/kandy.jpg",
    match: 92,
    match_percentage: 92,
    distance: "115 km",
    time: "2h 30m",
    bestTime: "Morning",
  },
  {
    label: "Day 4: Nuwara Eliya",
    title: "Nuwara Eliya Tea Hills",
    place_name: "Nuwara Eliya Tea Hills",
    city: "Nuwara Eliya",
    location: "Nuwara Eliya, Central Province",
    category: "Farms",
    lat: 6.9497,
    lng: 80.7891,
    day: 4,
    info: "Hill country tea estates, waterfalls, cool misty weather and scenic views.",
    why_we_recommend:
      "Hill country tea estates, waterfalls, cool misty weather and scenic views.",
    emoji: "🍃",
    image: "/places/nuwara-eliya.jpg",
    match: 91,
    match_percentage: 91,
    distance: "76 km",
    time: "2h 15m",
    bestTime: "Morning",
  },
  {
    label: "Day 5: Ella Rock Sunrise",
    title: "Ella Rock Sunrise",
    place_name: "Ella Rock Sunrise",
    city: "Ella",
    location: "Ella, Uva Province",
    category: "Nature & Wildlife Areas",
    lat: 6.8667,
    lng: 81.0466,
    day: 5,
    info: "Epic sunrise hike with beautiful valleys, tea fields and mountain views.",
    why_we_recommend:
      "Epic sunrise hike with beautiful valleys, tea fields and mountain views.",
    emoji: "🌅",
    image: "/places/ella.jpg",
    match: 90,
    match_percentage: 90,
    distance: "60 km",
    time: "1h 50m",
    bestTime: "Sunrise",
  },
  {
    label: "Day 6: Mirissa Whale Watching",
    title: "Mirissa Beach",
    place_name: "Mirissa Beach",
    city: "Mirissa",
    location: "Mirissa, Southern Province",
    category: "Beaches",
    lat: 5.9483,
    lng: 80.455,
    day: 6,
    info: "Whale watching, golden beaches, coconut trees and sunset vibes.",
    why_we_recommend:
      "Whale watching, golden beaches, coconut trees and sunset vibes.",
    emoji: "🐋",
    image: "/places/mirissa.jpg",
    match: 89,
    match_percentage: 89,
    distance: "138 km",
    time: "2h 45m",
    bestTime: "Afternoon",
  },
  {
    label: "Day 7: Galle Fort",
    title: "Galle Fort",
    place_name: "Galle Fort",
    city: "Galle",
    location: "Galle, Southern Province",
    category: "Historic Sites",
    lat: 6.0269,
    lng: 80.217,
    day: 7,
    info: "Dutch colonial fort, ocean views, cafes, boutique shops and heritage streets.",
    why_we_recommend:
      "Dutch colonial fort, ocean views, cafes, boutique shops and heritage streets.",
    emoji: "🏰",
    image: "/places/galle.jpg",
    match: 88,
    match_percentage: 88,
    distance: "45 km",
    time: "1h 10m",
    bestTime: "Evening",
  },
];

export const INTERESTS = [
  { id: "beach", label: "BEACH LIFE", emoji: "🏖️", queryText: "beaches and surfing" },
  { id: "mountain", label: "MOUNTAIN HIKING", emoji: "⛰️", queryText: "hiking and mountains" },
  { id: "culture", label: "CULTURAL HERITAGE", emoji: "🏛️", queryText: "cultural heritage and historic places" },
  { id: "wildlife", label: "WILDLIFE SAFARI", emoji: "🐘", queryText: "wildlife safari and national parks" },
];

export const DAY_COLORS = {
  1: "#60a5fa",
  2: "#facc15",
  3: "#f97316",
  4: "#34d399",
  5: "#a78bfa",
  6: "#38bdf8",
  7: "#f472b6",
  8: "#fb923c",
  9: "#22d3ee",
  10: "#fde047",
  11: "#c084fc",
  12: "#4ade80",
};

export const TABS = [
  { id: "recommendations", label: "RECOMMENDATIONS", icon: "☆" },
  { id: "accommodation", label: "ACCOMMODATION", icon: "▱" },
  { id: "itinerary", label: "ITINERARY", icon: "▣" },
];